libp2p/js-libp2p-interfaces

.gitignore, src/crypto/README.md, src/crypto/errors.js
Adds a new error code for when a peer fails to provide sufficient data to create a valid crypto exchange.
=> feat: crypto errors

src/topology/multicodec-topology.js, src/topology/tests/multicodec-topology.js
The condition to check if the peer has a multicodec of the topology was always true
=> fix: multicodec topology update peers with multicodec

package.json
The [package-table](https://www.npmjs.com/package/package-table) package needs this to create a well-formed package table
=> chore: add lead maintainer property

src/connection/connection.js, src/topology/multicodec-topology.js
The polyfill is big, we can simulate it by throwing an Error and it doesn't work under React Native.
=> fix: remove use of assert module

src/content-routing/README.md, src/peer-routing/README.md
=> fix: content and peer routing multiaddrs property

package.json
#74 added types generation on release with aegir. However, an old script was not removed
=> chore: remove old pre release script

src/pubsub/index.js, src/pubsub/peer-streams.js, src/types.ts
Twin PR of https://github.com/libp2p/js-libp2p/pull/864
=> fix: event emitter types with local types

src/connection/connection.js
Allows reusing the type for the new stream muxer function
=> chore: update pubsub interface

packages/compliance-tests/package.json, packages/compliance-tests/src/pubsub/connection-handlers.js, packages/compliance-tests/src/pubsub/multiple-nodes.js, packages/compliance-tests/src/stream-muxer/mega-stress-test.js, packages/compliance-tests/src/stream-muxer/stress-test.js, packages/interfaces/package.json
Control them with global --timeout settings instead as some CI systems have worse performance than others.
=> fix: remove timeouts

packages/interfaces/src/peer-id/types.d.ts
Adds missing method to be compatible with existing peer-id class.
=> chore: fix types

packages/compliance-tests/src/pubsub/api.js, packages/interfaces/src/pubsub/index.js, packages/interfaces/test/pubsub/emit-self.spec.js, packages/interfaces/test/pubsub/pubsub.spec.js, packages/interfaces/test/pubsub/utils/index.js
After the async peerstore changes registrar.register is now async
=> fix: registrar.register is now async

packages/compliance-tests/src/pubsub/connection-handlers.js, packages/compliance-tests/src/pubsub/emit-self.js, packages/compliance-tests/src/pubsub/messages.js, packages/compliance-tests/src/pubsub/multiple-nodes.js, packages/compliance-tests/src/pubsub/two-nodes.js, packages/interfaces/test/pubsub/lifesycle.spec.js, packages/interfaces/test/pubsub/pubsub.spec.js, packages/interfaces/test/pubsub/topic-validators.spec.js
Pubsub start/stop is now async
=> fix: async pubsub startup

packages/compliance-tests/src/peer-id/index.js, packages/interfaces/src/peer-id/types.d.ts
Also export CreateOptions and PeerIdJSON types
Co-authored-by: Alex Potsides <alex@achingbrain.net>
=> fix: peer-id privKey and pubKey can be undefined

packages/libp2p-interfaces/package.json
=> fix: correct errors path in exports map

.github/workflows/main.yml, package.json
Dedupe steps in main.yml and run release in each package
=> chore: update build

package.json, packages/libp2p-connection/package.json, packages/libp2p-interface-compliance-tests/package.json, packages/libp2p-interfaces/package.json, packages/libp2p-peer-id-factory/package.json, packages/libp2p-peer-id/package.json, packages/libp2p-pubsub/package.json, packages/libp2p-topology/package.json
=> chore: add semantic release config

packages/interfaces/src/crypto/types.d.ts
=> fix: update remote early data type

packages/libp2p-interface-compliance-tests/package.json, packages/libp2p-interface-compliance-tests/src/stream-muxer/base-test.ts, packages/libp2p-interface-compliance-tests/src/stream-muxer/close-test.ts, packages/libp2p-interface-compliance-tests/src/stream-muxer/index.ts, packages/libp2p-interface-compliance-tests/src/stream-muxer/mega-stress-test.ts, packages/libp2p-interface-compliance-tests/src/stream-muxer/spawner.ts, packages/libp2p-interface-compliance-tests/src/stream-muxer/stress-test.ts, packages/libp2p-interface-compliance-tests/src/transport/utils/index.ts, packages/libp2p-interfaces/src/stream-muxer/index.ts, packages/libp2p-pubsub/package.json
Ensure we pipe the muxer and not the muxed streams otherwise data does not flow.
=> fix: fix muxer tests

packages/libp2p-interface-compliance-tests/src/utils/mock-registrar.ts, packages/libp2p-interfaces/src/dht/index.ts, packages/libp2p-interfaces/src/registrar/index.ts, packages/libp2p-pubsub/src/index.ts, packages/libp2p-pubsub/test/emit-self.spec.ts, packages/libp2p-pubsub/test/instance.spec.ts, packages/libp2p-pubsub/test/lifecycle.spec.ts, packages/libp2p-pubsub/test/message.spec.ts, packages/libp2p-pubsub/test/pubsub.spec.ts, packages/libp2p-pubsub/test/topic-validators.spec.ts, packages/libp2p-pubsub/test/utils/index.ts, packages/libp2p-pubsub/tsconfig.json, packages/libp2p-topology/src/index.ts, packages/libp2p-topology/src/multicodec-topology.ts
Let libp2p chain through to the registrar instead of splitting the logic`
=> fix: make registrar simpler

packages/libp2p-interface-compliance-tests/src/stream-muxer/stress-test.ts
=> fix: increase stream test timeout

packages/libp2p-interfaces/src/dht/index.ts, packages/libp2p-logger/package.json, packages/libp2p-logger/src/index.ts
Also adds log formatter for datastore keys
=> fix: remove unused dht query option

packages/libp2p-logger/package.json, packages/libp2p-logger/src/index.ts, packages/libp2p-logger/tsconfig.json
=> feat: add trace option to logger

packages/libp2p-interface-compliance-tests/src/index.ts, packages/libp2p-interface-compliance-tests/src/peer-discovery/index.ts, packages/libp2p-interface-compliance-tests/src/pubsub/connection-handlers.ts, packages/libp2p-interface-compliance-tests/src/pubsub/emit-self.ts, packages/libp2p-interface-compliance-tests/src/pubsub/messages.ts, packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts, packages/libp2p-interface-compliance-tests/src/pubsub/two-nodes.ts
Adds methods to start/stop components also calling beforeStart/afterStart etc.
=> fix: add method for startable lifecyle

packages/libp2p-interfaces/src/dht/index.ts, packages/libp2p-interfaces/src/keychain/index.ts, packages/libp2p-interfaces/src/metrics/index.ts, packages/libp2p-interfaces/src/pubsub/index.ts, packages/libp2p-pubsub/src/utils.ts
Also simplifies DHT validators/selectors.
=> fix: add keychain types, fix bigint types

package.json, packages/libp2p-peer-id-factory/package.json, packages/libp2p-peer-id-factory/src/index.ts, packages/libp2p-peer-id-factory/src/proto.ts, packages/libp2p-peer-record/package.json, packages/libp2p-peer-record/src/envelope/envelope.ts, packages/libp2p-peer-record/src/peer-record/peer-record.ts, packages/libp2p-peer-store/package.json, packages/libp2p-peer-store/src/pb/peer.ts, packages/libp2p-pubsub/package.json, packages/libp2p-pubsub/test/message/rpc.ts
=> fix: regenerate protobuf code

packages/libp2p-connection/package.json, packages/libp2p-peer-record/package.json, packages/libp2p-peer-store/package.json
semantic-release-monorepo should really do this.
=> fix: update sibling deps

packages/interface-mocks/package.json, packages/interface-mocks/src/muxer.ts, packages/interface-pubsub/package.json
Updates to latest version of it-pushable.
=> chore: update it-pushable dep

packages/interface-mocks/src/connection.ts, packages/interface-mocks/src/muxer.ts, packages/interface-stream-muxer-compliance-tests/package.json, packages/interface-stream-muxer-compliance-tests/src/base-test.ts, packages/interface-stream-muxer-compliance-tests/src/close-test.ts, packages/interface-stream-muxer-compliance-tests/src/mega-stress-test.ts, packages/interface-stream-muxer-compliance-tests/src/stress-test.ts, packages/interface-stream-muxer/package.json, packages/interface-stream-muxer/src/index.ts
Simplifies muxer construction.
=> fix: remove components from muxer factory function

packages/interface-mocks/src/registrar.ts, packages/interface-registrar/src/index.ts
=> fix: update stream handler args

packages/interface-pubsub/src/index.ts
Adds `maxInboundStreams` and `maxOutboundStreams` for pubsub streams
=> fix: add stream control for pubsub

packages/interface-address-manager/package.json, packages/interface-compliance-tests/package.json, packages/interface-connection-compliance-tests/package.json, packages/interface-connection-encrypter-compliance-tests/package.json, packages/interface-connection-encrypter/package.json, packages/interface-connection-manager/package.json, packages/interface-connection/package.json, packages/interface-content-routing/package.json, packages/interface-dht/package.json, packages/interface-keychain/package.json, packages/interface-keys/package.json, packages/interface-metrics/package.json, packages/interface-mocks/package.json, packages/interface-peer-discovery-compliance-tests/package.json, packages/interface-peer-discovery/package.json, packages/interface-peer-id/package.json, packages/interface-peer-info/package.json, packages/interface-peer-routing/package.json, packages/interface-pubsub-compliance-tests/package.json, packages/interface-pubsub/package.json, packages/interface-record-compliance-tests/package.json, packages/interface-record/package.json, packages/interface-registrar/package.json, packages/interface-stream-muxer-compliance-tests/package.json, packages/interface-stream-muxer/package.json, packages/interface-transport-compliance-tests/package.json, packages/interface-transport/package.json, packages/interfaces/package.json
=> chore: update deps

packages/interface-peer-store/package.json
=> fix: update peer store interface deps

packages/interface-address-manager/package.json, packages/interface-connection-encrypter-compliance-tests/package.json, packages/interface-connection-encrypter-compliance-tests/src/utils/index.ts, packages/interface-connection-manager/package.json, packages/interface-connection/package.json, packages/interface-mocks/package.json, packages/interface-mocks/src/connection-encrypter.ts, packages/interface-mocks/src/multiaddr-connection.ts, packages/interface-mocks/src/peer-discovery.ts, packages/interface-peer-discovery-compliance-tests/package.json, packages/interface-peer-discovery-compliance-tests/src/index.ts, packages/interface-peer-info/package.json, packages/interface-transport-compliance-tests/package.json, packages/interface-transport/package.json
Updates all use of @multiformats/multiaddr
=> deps: update @multiformats/multiaddr to 11.0.0

README.md, packages/interface-address-manager/README.md, packages/interface-compliance-tests/README.md, packages/interface-connection-compliance-tests/README.md, packages/interface-connection-encrypter-compliance-tests/README.md, packages/interface-connection-encrypter/README.md, packages/interface-connection-manager/README.md, packages/interface-connection/README.md, packages/interface-content-routing/README.md, packages/interface-dht/README.md, packages/interface-keychain/README.md, packages/interface-keys/README.md, packages/interface-metrics/README.md, packages/interface-mocks/README.md, packages/interface-peer-discovery-compliance-tests/README.md, packages/interface-peer-discovery/README.md, packages/interface-peer-id/README.md, packages/interface-peer-info/README.md, packages/interface-peer-routing/README.md, packages/interface-peer-store/README.md, packages/interface-pubsub-compliance-tests/README.md, packages/interface-pubsub/README.md, packages/interface-record-compliance-tests/README.md, packages/interface-record/README.md, packages/interface-registrar/README.md, packages/interface-stream-muxer-compliance-tests/README.md, packages/interface-stream-muxer/README.md, packages/interface-transport-compliance-tests/README.md, packages/interface-transport/README.md, packages/interfaces/README.md
=> docs: update project config

packages/interface-keychain/src/index.ts
Adds method from keychain implementation that is missing from interface
=> fix: add missing method to keychain interface to rotate password

packages/interface-registrar/src/index.ts
The comments about default limits were out of date.
=> docs: update comments on registrar interface

packages/interface-address-manager/package.json, packages/interface-connection-encrypter-compliance-tests/package.json, packages/interface-connection-gater/package.json, packages/interface-connection-manager/package.json, packages/interface-connection/package.json, packages/interface-libp2p/package.json, packages/interface-mocks/package.json, packages/interface-peer-discovery-compliance-tests/package.json, packages/interface-peer-info/package.json, packages/interface-peer-store/package.json, packages/interface-transport-compliance-tests/package.json, packages/interface-transport/package.json
=> deps: update @multiformats/multiaddr to 12.0.0

packages/interface-mocks/src/duplex.ts
Updates to be compatible with mock multiaddr connection
=> fix: update mock duplex type
