- README.md
Crypto interface was missing in the README
> docs: add crypto to readme

- src/topology/index.js
- src/topology/multicodec-topology.js
Add `class-is` to topology, in order to allow registrar to validate the parameter
> feat: add class-is to topology

- src/topology/multicodec-topology.js
- src/topology/tests/multicodec-topology.js
As specified in the [readme](https://github.com/libp2p/js-interfaces/blob/master/src/topology/README.md#multicodec-topology-1) and used in [js-libp2p-pubsub](https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L186), as well as to be consistent with `onConnect`, the parameters should not be an object but a single parameter with the `peerInfo`
> fix: multicodec topology disconnect with peer param

- src/content-routing/README.md
> docs: corrected reference to delegated content routing

- src/connection/README.md
- src/connection/connection.js
- src/connection/status.js
- src/connection/tests/connection.js
This exports the Connection status' and uses them internally, so they can be more consistently used by other libraries.
> feat: export connection status'

- package.json
- src/transport/tests/listen-test.js
Fixed per discussion on [libp2p/js-libp2p#523#discussion_r359997872](https://github.com/libp2p/js-libp2p/pull/523#discussion_r359997872)
> fix: transport should not handle connection if upgradeInbound throws

- src/crypto/README.md
- src/crypto/errors.js
resolves #8 
* Adds the `InvalidCryptoTransmissionError` Error to the crypto exports.
> feat: add crypto transmission error

- src/connection/README.md
- src/connection/connection.js
- test/connection/index.spec.js
Not every transport is going to know the remote address of a new connection when it is created, such as a WebRTC connection in browser. While we can eventually determine an observed address, requiring it at Connection creation is not reasonable.
Using webrtc as an example, there is no valid remote address for a peer we received an incoming address from. A valid multiaddr for the peer would be the signaling server we connected through, plus the id of the peer. We don't know the id of the remote peer until Crypto runs during the upgrade process. In theory, we could assemble the remoteAddress before Connection creation, but it requires context of the Transport dialing it. Rather than coding for n number of transports in the libp2p dialer, it would be better to create the upgraded connection …
> fix(connection): dont require remoteAddr on creation

- src/transport/tests/listen-test.js
This makes the listener test a bit more resilient by waiting for both listener side connections to be fully established before executing the close. The current setTimeout of 0 isn't sufficient for slower connection establishment (like webrtc signaling).
> fix(transport): make close listener test more resilient

- package.json
Currently, transports must have `it-pipe` and `it-pair` in their dependencies, otherwise they are not able to run the interface tests
> fix: dependencies for tests should not be needed by who requires the tests

- src/connection/connection.js
- src/connection/tests/connection.js
- test/connection/compliance.spec.js
`connection.addStream` was not being properly called internally. This would cause stream protocols to not be tracked properly. This also adds a test to the interface to ensure connection implementations are properly removing streams from tracking when `stream.close()` is called.
> fix(connection): tracks streams properly

- src/peer-discovery/tests/index.js
After checking failures on `peer-discovery` tests for https://github.com/libp2p/js-libp2p-pubsub-peer-discovery/pull/5 I realized that emittery `.once()` returns a promise and does not support a listener callback, like in node.
As a consequence of this inconsistency, we should probably use `.on()` since we are already removing all the listeners on afterEach
> chore: discovery should not use once

- src/content-routing/README.md
- src/peer-routing/README.md
In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR removes the `peer-info` usage on the `content-routing` and `peer-routing` interfaces.
- `findPeer`
Returns `Promise<{ id: CID, addrs: Multiaddr[] }>` instead of a `PeerInfo`
- `findProviders`
Returns `AsyncIterable<{ id: CID, addrs: Multiaddr[] }>` instead of `AsyncIterable<PeerInfo>`
BREAKING CHANGE: content-routing and peer-routing APIs return an object with relevant properties instead of peer-info
> chore: update content and peer routing interfaces removing peer-info

- src/topology/README.md
- src/topology/index.js
- src/topology/multicodec-topology.js
- src/topology/tests/multicodec-topology.js
- src/topology/tests/topology.js
- test/topology/mock-peer-store.js
- test/topology/multicodec-topology.spec.js
In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR removes the `peer-info` usage on topology.
This changes have impact on pubsub modules, as well as the dht
BREAKING CHANGE: topology api now uses peer-id instead of peer-info
> chore: remove peer-info usage on topology

- src/topology/multicodec-topology.js
- src/topology/tests/multicodec-topology.js
- test/topology/mock-peer-store.js
- test/topology/multicodec-topology.spec.js
Considering a scenario where Peer A and B start, connect to each other using a multicodec topology. Then, Peer B restarts, it is still not connected to A. It will run the update peers: https://github.com/libp2p/js-libp2p-interfaces/blob/master/src/topology/multicodec-topology.js#L68 but it does not have a connection to A yet, so it will not call onConnect. After this, identify will run, but the protocols will not change and the protocol change handler will not be called.
Fixes https://github.com/libp2p/js-libp2p/issues/658
> fix: reconnect should trigger topology on connect if protocol stored

- README.md
- src/record/README.md
- src/record/index.js
- src/record/tests/index.js
This PR adds the `record-interface`.
The `record-interface` primary goal is to guarantee that any record implementation will be compliant with the expectations of a libp2p **envelope**.
`js-libp2p` will start by having a single implementation of the `record-interface`, known as a `peer-record`. This implementations will be used to share peers' multiaddrs across the network with security guarantees, thanks to the libp2p envelope where the records will be wrapped into.
Open questions:
- Should we have tests for the unmarshal operation in the interface tests? I think that we should have the unmarshal and then rely on `isEqual` to verify if the unmarshal operation resulted in the same content as before the marshal
A record implementation will now look as follows:
```js
class PeerRecord …
```
> feat: record interface

- package.json
Updates libp2p-tcp to a version that depends on the same multiaddr as this module.
> chore: update libp2p-tcp

- package.json
- src/crypto/tests/index.js
- src/record/README.md
- src/record/index.js
- src/record/tests/index.js
- src/stream-muxer/tests/close-test.js
- src/transport/tests/listen-test.js
This replaces the remaining usages of Buffer with Uint8Array.
BREAKING CHANGE: this changes the API of records and updates several tests to use Uint8Arrays
required by https://github.com/libp2p/js-libp2p/pull/730
> fix: replace remaining Buffer usage with Uint8Array

- src/pubsub/index.d.ts
- src/pubsub/index.js
- src/pubsub/utils.d.ts
- src/pubsub/utils.js
- test/pubsub/utils.spec.js
See https://github.com/libp2p/specs/pull/285
BREAKING CHANGE:
new getMsgId return type is not backwards compatible with prior `string`
return type.
> feat: update pubsub getMsgId return type to Uint8Array

- package.json
- src/pubsub/README.md
- src/pubsub/errors.js
- src/pubsub/index.js
- src/pubsub/signature-policy.js
- src/pubsub/utils.js
- test/pubsub/message.spec.js
- test/pubsub/topic-validators.spec.js
See https://github.com/libp2p/specs/pull/294 and https://github.com/libp2p/specs/pull/299
Add a "global" signature policy to pubsub. This is a first-step towards having a "topic-specific" signature policy as described in the specs.
This "signature policy" replaces the ad-hoc options `signMessages` and `strictSigning` that were previously in use.
Only 'StrictSign' and 'StrictNoSign' signature policies are implemented, the 'LaxSign' and 'LaxNoSign' signature policies are not recommended and will be deprecated, so are not included.
BREAKING CHANGE:
`signMessages` and `strictSigning` pubsub configuration options replaced
with a `globalSignaturePolicy` option
> feat: pubsub: add global signature policy

- src/pubsub/errors.d.ts
- src/pubsub/index.d.ts
- src/pubsub/index.js
- src/pubsub/signature-policy.d.ts
- src/pubsub/utils.d.ts
Unfortunately, #66, as merged, had several errors with the typescript types:
- the globalSignaturePolicy type was set as `SignaturePolicy`, rather than `string`
- the idea is that `SignaturePolicy` is the "type" of the enum, which is how this would be described if this was written in typescript. Unfortunately, this type was not exported so there was a type mismatch.
- the checked-in typescript declaration files were not updated
This PR rectifies both issues
> pubsub: fix typescript types

- src/pubsub/tests/api.js
- src/pubsub/tests/messages.js
- src/pubsub/tests/multiple-nodes.js
- src/pubsub/utils.js
Sorry for the many insufficient PRs.
In the future, it may be wise to always open a PR in a 'consumer' of the interface being updated, in conjunction with the PR updating the interface, to make sure there are no surprises.
I've done that now, with https://github.com/ChainSafe/js-libp2p-gossipsub/pull/145 which should pass tests when using this PR.
This PR includes minimal changes required to fix the conformance tests.
> Pubsub conformance test updates

- README.md
This PR adds the pubsub interface link to the readme, which was missing.
> chore: add pubsub interface to readme

- src/connection/connection.js
The comment says it can be 'inbound' or 'outbound' so constrain the type to those values.
> fix: specify connection direction

- src/index.js
- src/pubsub/index.js
- src/pubsub/peer-streams.js
- src/types.d.ts
Adds dht selectors and validators here to be used across the board easily. 
Also removes unecessary EventEmitter types, as this was already fixed
> chore: add dht selectors and validators

- packages/interfaces/package.json
- packages/interfaces/src/pubsub/index.js
https://github.com/libp2p/js-libp2p-interfaces/pull/103 subtlely changed the pubsub rpc/message processing pipeline from fully concurrent to fully sequential. This is subtle because it seems the only part of processing that may be asynchronous is message validation. So in many cases, when message validation is not heavy, or when few messages are received, no delay in rpc/message processing is detectable.
This PR restores the original behavior, of allowing rpc/messages to be processed concurrently, but with care of ensuring that errors are handled and will not propagate to a top-level unhandled exception.
> fix: allow pubsub rpc to be processed concurrently

- packages/interfaces/src/crypto/types.d.ts
Add PublicKey and PrivateKey from libp2p-crypto so we can depend
on the interface here without pulling in all of libp2p-crypto.
> feat: add public and private key interfaces

- packages/libp2p-connection/test/index.spec.ts
- packages/libp2p-interfaces-compliance-tests/src/transport/dial-test.ts
- packages/libp2p-interfaces-compliance-tests/src/transport/listen-test.ts
- packages/libp2p-interfaces-compliance-tests/src/transport/utils/index.ts
- packages/libp2p-interfaces-compliance-tests/test/connection/index.spec.ts
- packages/libp2p-interfaces/src/stream-muxer/index.ts
- packages/libp2p-interfaces/src/transport/index.ts
The `mockUpgrader` is supposed to accept a `MultiaddrConnection` and return a `Connection`, but it just passes through the `MultiaddrConnection`.
This is a problem as the two types are not compatible.  This shows up in our code as our tests treat `Connection`s as if they are something you can pass to `it-pipe` but they are not, you have to get a `MuxedStream` from `conn.netStream([str])` for that.
This PR fixes up the `mockUpgrader` to return something compatible with the `Connection` interface.  It also removes a few of the dialer tests that were only testing the newly introduced mock code.
> fix: update dialer tests

- packages/interfaces/src/crypto/types.d.ts
- packages/interfaces/src/transport/types.d.ts
- packages/interfaces/src/types.d.ts
Allow passing AbortSignals in to connection upgrading and encryption
so the operations can be aborted if a timeout is reached.
> fix: make connection upgrade and encryption abortable

- packages/interfaces/src/stream-muxer/types.d.ts
- packages/interfaces/src/transport/types.d.ts
`BufferList` is exported from `'bl/BufferList'` not `'bl'` and the `source` arg for `Sink` should be an `AsyncIterable<Uint8Array>` not a `Uint8Array`.
It should also be symmetrical with `Source` - e.g., both are `AsyncIterable<Uint8Array | BufferList>`.
> fix: BufferList imports and MuxedStream sinks

- packages/interfaces/src/crypto/types.d.ts
- packages/interfaces/src/transport/types.d.ts
This is the wrong fix - the maconn should be aborted at the source rather than each use of it.  We have a `TimeoutController` that is passed in to the connection that should abort it if the upgrade/crypto handshake isn't completed in time, but at the moment `abortable-iterator` doesn't reject when reads stall indefinitely - fix for that in https://github.com/alanshaw/abortable-iterator/pull/15
> fix: revert upgrader/crypto options

- packages/libp2p-interfaces/src/crypto/index.ts
- packages/libp2p-interfaces/src/transport/index.ts
Reverts libp2p/js-libp2p-interfaces#121 - see explanation in https://github.com/libp2p/js-libp2p-interfaces/pull/124
> chore: revert "fix: make connection upgrade and encryption abortable"

- packages/compliance-tests/src/pubsub/connection-handlers.js
- packages/compliance-tests/src/topology/multicodec-topology.js
- packages/compliance-tests/test/topology/mock-peer-store.js
- packages/compliance-tests/test/topology/multicodec-topology.spec.js
- packages/interfaces/src/topology/index.js
- packages/interfaces/src/topology/multicodec-topology.js
Refactors interfaces and classes used by `libp2p-interfaces` to use the async peer store from https://github.com/libp2p/js-libp2p/pull/1058
BREAKING CHANGE: peerstore methods are now all async
> feat: async peer store

- packages/compliance-tests/src/peer-id/index.js
- packages/interfaces/src/peer-id/types.d.ts
In the PR https://github.com/libp2p/js-libp2p-interfaces/pull/107  the `PeerId` interface was introduced. Later in the PR https://github.com/libp2p/js-libp2p-interfaces/pull/111/ that was refactored and some intentional changes introduced. 
The `privKey` and `pubKey` both can be undefined depending on the data, more details can be found in the PR https://github.com/libp2p/js-peer-id/pull/150.
The `PeerId` object can be created with the following scenarios: 
1. `new` in that case both keys are optional 
2. `PeerId.create` in that case if provided input is valid than both keys exists 
3. `PeerId.createFromBytes`, `PeerId.createFromB58String`, `PeerId.createFromHexString`, `PeerId.createFromCID`  in these cases public key _can_ be decoded but private key don't exists 
4. …
> fix: peer-id privKey and pubKey can be undefined

- packages/interfaces/src/peer-id/types.d.ts
A PeerId's privKey and/or pubKey can be undefined but we've got types
that say they cannot.
These fields are accessed when a node is interacting with it's own
PeerId so these fields are set, but really they can be undefined.
Marking these fields as undefined was a breaking change so this PR
partially reverts #131 - the proper fix is in the 4.x.x release line
which should be used in preference to 2.x.x.
> fix: partial revert of 131 for v2.x.x

- packages/libp2p-connection/package.json
- packages/libp2p-interface-compliance-tests/package.json
- packages/libp2p-interfaces/package.json
- packages/libp2p-interfaces/src/transport/index.ts
- packages/libp2p-peer-id-factory/package.json
- packages/libp2p-peer-id/package.json
- packages/libp2p-pubsub/package.json
- packages/libp2p-topology/package.json
semantic-release-monorepo doesn't do this either and without this you get duplicate versions when running `npm i` in this repo.
See: https://github.com/pmowrer/semantic-release-monorepo/issues/92
> chore: update package versions

- packages/compliance-tests/src/peer-id/index.js
- packages/interfaces/src/peer-id/types.d.ts
See #138 for discussion - will re-release #131 as v5.x.x to enable managing the transition since it will require a breaking release of the peer-id module.
> fix: partial revert of 131 for v4.x.x

- packages/interfaces/src/peer-id/types.d.ts
Because the `.privKey` property can be undefined, so can the return value from `.marshalPrivKey`
Reimplements #131 - see #138 for discussion.
BREAKING CHANGE: `.privKey` and `.pubKey` properties can be undefined, so can the return type from `.marshalXXKey`
> fix: PeerId.marshalPrivKey can return undefined

- packages/compliance-tests/package.json
- packages/compliance-tests/src/peer-id/index.js
- packages/compliance-tests/src/stream-muxer/close-test.js
- packages/compliance-tests/src/transport/dial-test.js
- packages/interfaces/package.json
- packages/interfaces/src/pubsub/peer-streams.js
- packages/interfaces/src/transport/README.md
AbortController is global in all supported environments so there's
no need to use the polyfill any more.
> fix: remove abort controller polyfill

- packages/interfaces/src/pubsub/index.js
**Motivation**
+ As a consumer of this library, Lodestar would like to know peers that a message sent to in `publish()` method
+ This is a breaking change to the pubsub interface
See https://github.com/libp2p/js-libp2p-interfaces/pull/119#issuecomment-1016696876
>   feat: pubsub: publish return number of recipients

- packages/libp2p-interface-compliance-tests/src/connection/connection.ts
- packages/libp2p-interface-compliance-tests/src/crypto/utils/index.ts
- packages/libp2p-interface-compliance-tests/src/transport/dial-test.ts
- packages/libp2p-interface-compliance-tests/src/transport/utils/index.ts
- packages/libp2p-interfaces/src/connection/index.ts
- packages/libp2p-interfaces/src/peer-id/index.ts
- packages/libp2p-interfaces/src/transport/index.ts
- packages/libp2p-peer-id/src/index.ts
Trying to cut the number of fields objects have down - some of these should be obvious from the context - our own peer id, etc.
> fix: remove extra fields

- packages/libp2p-interfaces/src/index.ts
- packages/libp2p-interfaces/src/peer-discovery/index.ts
Peer discovery methods are expected to be startable according to the compliance tests, so make the discovery interface extend startable.
> fix: make discovery startable

- packages/libp2p-interfaces/src/index.ts
- packages/libp2p-logger/CHANGELOG.md
- packages/libp2p-logger/LICENSE
- packages/libp2p-logger/LICENSE-APACHE
- packages/libp2p-logger/LICENSE-MIT
- packages/libp2p-logger/README.md
- packages/libp2p-logger/package.json
- packages/libp2p-logger/src/index.ts
- packages/libp2p-logger/test/index.spec.ts
- packages/libp2p-logger/tsconfig.json
- packages/libp2p-pubsub/src/index.ts
- packages/libp2p-pubsub/src/peer-streams.ts
Adds @libp2p/logger for use in libp2p components.
Currently wraps debug but lets us swap it out in future - for example
if it doesn't go to ESM in a reasonable timeframe.
> feat: add logger package

- packages/libp2p-interface-compliance-tests/src/transport/listen-test.ts
- packages/libp2p-interfaces/src/transport/index.ts
Cannot return a Connection on listen because we don't have one until a peer connects to the listener.
> fix: remove args from listener events

- packages/libp2p-interface-compliance-tests/src/mocks/connection.ts
- packages/libp2p-interface-compliance-tests/src/transport/utils/index.ts
- packages/libp2p-interface-compliance-tests/test/crypto/mock-crypto.ts
- packages/libp2p-interfaces/src/peer-id/index.ts
- packages/libp2p-peer-id-factory/src/index.ts
- packages/libp2p-peer-id-factory/test/index.spec.ts
- packages/libp2p-peer-id/src/index.ts
- packages/libp2p-peer-id/test/index.spec.js
- packages/libp2p-peer-id/tsconfig.json
- packages/libp2p-peer-record/src/envelope/index.ts
- packages/libp2p-peer-record/src/peer-record/index.ts
- packages/libp2p-peer-record/test/peer-record.spec.ts
- packages/libp2p-peer-store/src/address-book.ts
- packages/libp2p-peer-store/src/index.ts
- packages/libp2p-peer-store/src/key-book.ts
- packages/libp2p-peer-store/src/metadata-book.ts
- packages/libp2p-peer-store/src/proto-book.ts
- packages/libp2p-peer-store/src/store.ts
- packages/libp2p-peer-store/test/address-book.spec.ts
- packages/libp2p-peer-store/test/key-book.spec.ts
- packages/libp2p-peer-store/test/metadata-book.spec.ts
- packages/libp2p-peer-store/test/peer-store.spec.ts
- packages/libp2p-peer-store/test/proto-book.spec.ts
- packages/libp2p-pubsub/src/message/sign.ts
- packages/libp2p-pubsub/src/utils.ts
- packages/libp2p-pubsub/test/utils/index.ts
To avoid leaking concrete implementation classes, hide their defintion and creation behind factory methods that are typed to return the interfaces they implement.
> fix: hide implementations behind factory methods

- packages/libp2p-interface-compliance-tests/package.json
- packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/two-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/utils.ts
- packages/libp2p-interfaces/src/pubsub/index.ts
Some environments (e.g. browsers) are too slow and miss the subscription change events.
Instead, wait for the subscription change events explicitly.
> fix: remove delays from pubsub tests

- packages/libp2p-interfaces/src/content-routing/index.ts
There is no way of knowing where the result came from when talking to go-ipfs over http so remove the field.
> fix: update content routing get return type

- packages/libp2p-interface-compliance-tests/src/pubsub/api.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/connection-handlers.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/emit-self.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/index.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/messages.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/two-nodes.ts
- packages/libp2p-interfaces/src/pubsub/index.ts
- packages/libp2p-pubsub/package.json
- packages/libp2p-pubsub/src/index.ts
- packages/libp2p-pubsub/test/utils/index.ts
Changes `PubSub` to not be a generic type as we don't know the event types that will be emitted ahead of time.  Also, the message types for anything that isn't a subscription change is the same so there's little to gain type-wise from requiring knowledge of the event types.
> fix: update pubsub types

- packages/libp2p-interfaces/src/connection/index.ts
- packages/libp2p-interfaces/src/index.ts
- packages/libp2p-interfaces/src/peer-id/index.ts
- packages/libp2p-interfaces/src/topology/index.ts
- packages/libp2p-interfaces/src/transport/index.ts
Allows for more control over the lifecycle of `Startable`s. For example if you need to interact with another component before you can be considered ready, you can implement the `afterStart` method which will be invoked after all other components have had their `start` method called.
Similarly `beforeStop` will be called while all other components are still running, so if you need to interact with other components during the shutdown process this is the place to do it.
> fix: expand startable interface

- packages/libp2p-interface-compliance-tests/test/peer-discovery/mock-discovery.ts
- packages/libp2p-interfaces/package.json
- packages/libp2p-interfaces/src/content-routing/index.ts
- packages/libp2p-interfaces/src/dht/index.ts
- packages/libp2p-interfaces/src/peer-discovery/index.ts
- packages/libp2p-interfaces/src/peer-info/index.ts
- packages/libp2p-interfaces/src/peer-routing/index.ts
- packages/libp2p-interfaces/src/peer-store/index.ts
- packages/libp2p-peer-store/src/address-book.ts
- packages/libp2p-pubsub/package.json
Peer info is the term used elsewhere so rename for consistency.
> fix: rename peer data to peer info

- packages/libp2p-connection/package.json
- packages/libp2p-interface-compliance-tests/package.json
- packages/libp2p-interfaces/package.json
- packages/libp2p-logger/package.json
- packages/libp2p-multistream-select/package.json
- packages/libp2p-peer-collections/package.json
- packages/libp2p-peer-id-factory/package.json
- packages/libp2p-peer-id/package.json
- packages/libp2p-peer-record/package.json
- packages/libp2p-peer-store/package.json
- packages/libp2p-pubsub/package.json
- packages/libp2p-topology/package.json
- packages/libp2p-tracked-map/package.json
Use version of aegir that has version of `@semantic-release/github` that respects GitHub rate limiting so we can publish more reliably.
> chore: update aegir

- packages/libp2p-logger/src/index.ts
- packages/libp2p-peer-id/src/index.ts
- packages/libp2p-peer-id/test/index.spec.ts
- packages/libp2p-peer-store/src/store.ts
Adds logger methods used by ipfs, also tests the digest length not the multihash length when parsing PeerIds out of CIDs.
> fix: add logger methods, fix peer id deserialization

- packages/libp2p-interface-compliance-tests/src/pubsub/api.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/connection-handlers.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/emit-self.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/messages.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/two-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/utils.ts
- packages/libp2p-interfaces/src/pubsub/index.ts
- packages/libp2p-pubsub/src/index.ts
- packages/libp2p-pubsub/test/emit-self.spec.ts
- packages/libp2p-pubsub/test/pubsub.spec.ts
Instead of having arbitrary strings as event names, emit all incoming pubsub messages via the 'message' event.  Topic names can be discovered from the `type` property of the incoming `CustomEvent` and the `Message` object is accessible via the `detail` field.
This vastly simplifies typing the `PubSub` interface and means users don't have to worry about creating `CustomEvent` objects, they just call `.publish` with the topic name and the data they want to send.
> fix: emit pubsub messages using 'message' event

- packages/libp2p-interface-compliance-tests/src/pubsub/api.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/connection-handlers.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/emit-self.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/index.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/messages.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/two-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/utils.ts
- packages/libp2p-interfaces/src/pubsub/index.ts
- packages/libp2p-pubsub/package.json
- packages/libp2p-pubsub/src/index.ts
- packages/libp2p-pubsub/test/pubsub.spec.ts
Convert the PubSub interface compliance tests to only test the methods in the PubSub interface instead of the abstract subclass since it may not be used.
> fix: test PubSub interface and not PubSubBaseProtocol

- packages/libp2p-interface-compliance-tests/src/mocks/connection-manager.ts
- packages/libp2p-interface-compliance-tests/src/mocks/connection.ts
- packages/libp2p-interface-compliance-tests/src/mocks/registrar.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/api.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/connection-handlers.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/emit-self.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/messages.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/two-nodes.ts
- packages/libp2p-interface-compliance-tests/src/pubsub/utils.ts
- packages/libp2p-interfaces/src/pubsub/index.ts
- packages/libp2p-pubsub/src/index.ts
- packages/libp2p-pubsub/test/emit-self.spec.ts
- packages/libp2p-pubsub/test/instance.spec.ts
- packages/libp2p-pubsub/test/lifecycle.spec.ts
- packages/libp2p-pubsub/test/pubsub.spec.ts
- packages/libp2p-pubsub/test/utils/index.ts
Makes the publish method async as it needs to be to sign outgoing messages.
Also returns the peer IDs that a given message was sent to.
> fix: update pubsub interface in line with gossipsub

- packages/libp2p-interface-compliance-tests/src/pubsub/connection-handlers.ts
Some pubsub nodes live for longer than the test, shut them down after running the tests.
> fix: stop pubsub after test

- packages/libp2p-interface-compliance-tests/src/pubsub/multiple-nodes.ts
GossipSub needs the heartbeat to run before the mesh overlay is built - we need to wait for this to happen otherwise messages don't get gossiped onwards to peers.
> fix: add delays for gossipsub

- packages/libp2p-interface-compliance-tests/src/mocks/muxer.ts
- packages/libp2p-interfaces/src/components.ts
Since https://github.com/libp2p/js-libp2p/pull/1193 there will be values for pubsub and dht so no need to return them as maybe-undefined.
Also make mock-muxer logs a little less chatty.
> fix: pubsub and dht are always set

- packages/libp2p-interfaces/src/connection-manager/index.ts
Allow aborting the opening of a connection.
> fix: add abort options to open connection

- packages/libp2p-interface-compliance-tests/src/mocks/muxer.ts
- packages/libp2p-interface-compliance-tests/src/mocks/registrar.ts
- packages/libp2p-interfaces/src/connection-manager/index.ts
Do not return topology protocols, only ones that are handled.
Also do not throw error when a stream is missing, just send a reset.
> fix: only send handled protocols

- packages/libp2p-interface-compliance-tests/src/mocks/muxer.ts
- packages/libp2p-interface-compliance-tests/test/peer-discovery/mock-discovery.ts
- packages/libp2p-interfaces/src/peer-discovery/index.ts
So we can identify them from instances
> fix: add tag to peer discovery interface

- packages/libp2p-connection/package.json
- packages/libp2p-connection/src/index.ts
- packages/libp2p-connection/test/compliance.spec.ts
- packages/libp2p-connection/test/index.spec.ts
- packages/libp2p-interface-compliance-tests/src/mocks/connection.ts
- packages/libp2p-interface-compliance-tests/src/mocks/muxer.ts
- packages/libp2p-interface-compliance-tests/src/stream-muxer/close-test.ts
- packages/libp2p-interfaces/src/connection/index.ts
This adds tests for closeRead and closeWrite on the muxer streams.
Also:
- Removed libp2p-tcp in favor of it-pair to avoid circular deps
- Connection.close() will now close its internal streams to avoid lingering streams.
Supersedes #90
BREAKING CHANGE: This adds closeWrite and closeRead checks in the tests, which will cause test failures for muxers that don't implement those
> fix: close streams when connection is closed

- packages/libp2p-connection/package.json
- packages/libp2p-connection/tsconfig.json
- packages/libp2p-interface-compliance-tests/package.json
- packages/libp2p-logger/package.json
- packages/libp2p-multistream-select/package.json
- packages/libp2p-peer-collections/package.json
- packages/libp2p-peer-id-factory/package.json
- packages/libp2p-peer-id/package.json
- packages/libp2p-peer-record/package.json
- packages/libp2p-peer-store/package.json
- packages/libp2p-pubsub/package.json
- packages/libp2p-topology/package.json
- packages/libp2p-tracked-map/package.json
The build failed during release, looks like sibling deps don't get updated by semantic-release-monorepo properly.
> fix: update interfaces

- packages/libp2p-connection/src/index.ts
- packages/libp2p-connection/test/compliance.spec.ts
- packages/libp2p-connection/test/index.spec.ts
- packages/libp2p-interface-compliance-tests/src/mocks/connection.ts
- packages/libp2p-interface-compliance-tests/src/mocks/muxer.ts
- packages/libp2p-interfaces/src/connection/index.ts
Makes the `close`/`closeRead`/`closeWrite` methods synchronous the same as `abort`/`reset`
> fix: make stream return types synchronous

- packages/libp2p-pubsub/src/utils.ts
- packages/libp2p-pubsub/test/utils.spec.ts
For use by extending classes, expose methods for serializing/deserializing
sequence numbers.
> feat: expose utility methods to convert bigint to bytes and back

- packages/libp2p-interface-compliance-tests/src/mocks/muxer.ts
- packages/libp2p-interface-compliance-tests/src/stream-muxer/spawner.ts
When the remote closes us, only close for reading
> fix: only close muxed stream for reading

- packages/libp2p-interfaces/src/content-routing/README.md
- packages/libp2p-interfaces/src/peer-discovery/README.md
- packages/libp2p-interfaces/src/peer-routing/README.md
- packages/libp2p-interfaces/src/stream-muxer/README.md
- packages/libp2p-interfaces/src/transport/README.md
Fixes a typo that caused the [peer-discovery](https://github.com/libp2p/js-libp2p-interfaces/tree/master/packages/libp2p-interfaces/src/peer-discovery) badge not to appear in Github previews. 
Please note that other readmes in the libp2p-interfaces folder point to their old, deprecated and read-only repos (example: [peer-routing](https://github.com/libp2p/js-libp2p-interfaces/tree/master/packages/libp2p-interfaces/src/peer-routing)), whereas this one was set to point to the local images folder. Perhaps something should be done for consistency?
> fix: dead badge

- packages/libp2p-interfaces/src/events.ts
Specify what `EventMap` should look like in the generic type.
Fixes: #227
> fix: event emitter types

- packages/interface-stream-muxer-compliance-tests/src/stress-test.ts
The lastest playwright pulls a version of FireFox down that's very, very slow.
> fix: increase timeout for firefox

- packages/interface-mocks/package.json
- packages/interface-mocks/src/registrar.ts
- packages/interface-registrar/src/index.ts
Instead of one limit per connection, limit incoming and outgoing streams separately.
> feat: define stream limits as input/output

- packages/interface-connection/src/index.ts
- packages/interface-mocks/src/connection.ts
- packages/interface-mocks/src/muxer.ts
- packages/interface-stream-muxer-compliance-tests/src/base-test.ts
- packages/interface-stream-muxer-compliance-tests/src/close-test.ts
- packages/interface-stream-muxer-compliance-tests/src/spawner.ts
- packages/interface-stream-muxer/src/index.ts
- add `Direction` type alias in interface-connection
- add `direction?: Direction` to `StreamMuxerInit`
Resolves #252 
Resolves #250
> feat: add direction to StreamMuxerInit

- packages/interface-peer-store/src/index.ts
Allow tagging peers to better prioritise which connections to kill when hitting limits.  Also for keeping "priority" connections alive.
Refs: https://github.com/libp2p/js-libp2p/issues/369
BREAKING CHANGE: implementations will need to add the various tag methods
> feat!: add peer tagging

- packages/interface-peer-store/README.md
- packages/interface-peer-store/package.json
- packages/interface-peer-store/src/tags.ts
Exports a `KEEP_ALIVE` tag for reuse.
> feat: export common tags

- packages/interface-peer-id/README.md
The documentation currently points to the older version of `peer-id` and should be updated to point to the currently supported version.
> docs: update `peer-id` link to new implementation

- packages/interface-metrics/src/index.ts
To better support more sophisticated graphs, allow grouping metrics by a label and also passing a function to calculate either individual metrics or groups of metrics.
Fixes: #257
Fixes: #258
BREAKING CHANGE: the return type of `metrics.getComponentMetrics` has been changed to include optional labels/help text and also is now a function that returns a single or group value
> feat!: add metrics groups

- packages/interface-mocks/src/connection-manager.ts
`closeConnections` should close a connection with a peer reciprocally.
Fix bug where the reciprocal connection was not being closed.
> fix: mock connection manager close reciprocal connection

- packages/interface-pubsub/package.json
- packages/interface-pubsub/src/index.ts
To support no-copy operations, make stream input/output types `Uint8ArrayList`s instead of `Uint8Array`s.
BREAKING CHANGE: the inbound/outbound stream types have changed
> fix!: make stream types Uint8ArrayLists

- packages/interface-pubsub-compliance-tests/src/messages.ts
- packages/interface-pubsub-compliance-tests/src/two-nodes.ts
- packages/interface-pubsub/src/index.ts
BREAKING CHANGE: The `Message` type is now either a `StrictSignMessage`
or a `StrictNoSignMessage`
> feat!: pubsub Message types for signature policies

- packages/interface-record-compliance-tests/src/index.ts
- packages/interface-record/package.json
- packages/interface-record/src/index.ts
In order to support no-copy operations, allow use of `Uint8ArrayList`s in libp2p records.
BREAKING CHANGE: return type of .marshal method and several properties have changed
> fix!: make record property and return types lists

- .gitignore
- packages/interface-connection-encrypter-compliance-tests/package.json
- packages/interface-connection-encrypter-compliance-tests/src/index.ts
- packages/interface-connection-encrypter-compliance-tests/src/utils/index.ts
- packages/interface-connection-encrypter/package.json
- packages/interface-connection-encrypter/src/index.ts
- packages/interface-connection/package.json
- packages/interface-connection/src/index.ts
- packages/interface-mocks/src/connection-encrypter.ts
replacing #275 
BREAKING CHANGE: connection encryption interface now accepts and yields uint8arraylist instead of uint8array
> feat!: change connection encryption interface to uint8arraylist

- packages/interface-transport-compliance-tests/src/dial-test.ts
When testing the output of a stream, test byte value
> fix: compare bytes in transport test

- packages/interface-connection-encrypter/src/index.ts
In order to support connecting to mulitaddrs without a peer id make the remote peer id an optional argument when securing the outbound connection.
> fix: make outbound peer id optional

- packages/interface-connection-encrypter/src/index.ts
- packages/interface-mocks/src/connection-encrypter.ts
fixes https://github.com/libp2p/js-libp2p-interfaces/issues/291
earlyData in Noise has been deprecated in favor of a structured protobuf labeled Noise Extensions: https://github.com/libp2p/specs/pull/453.
remoteExtensions and earlyData are both Noise specific. I'm not sure what the value is by having this interface defined here. Probably what we want is a minimum interface that callers expect, but the concrete implementation can return anything as long as it meets the minimum interface. This is a bigger change than I want to take, but probably the better solution that we should do when we have other encryption modules.
BREAKING CHANGE: remoteEarlyData is replaced by generic remoteExtensions
> feat!: Add remoteExtensions to connection-encrypter

- packages/interface-connection-manager/src/index.ts
- packages/interface-mocks/src/connection-manager.ts
In order to check we can accept an incoming connection before exchanging PeerIds, add a method to the ConnectionManager interface that can be called by the upgrader.
> feat: add acceptIncomingConnection to ConnectionManager

- packages/interface-connection-encrypter/src/index.ts
Similar to the `ConnectionEncrypter` interface, specify a default type for the `Extension` so consumers uninterested in the `remoteExtensions` field can operate as before.
> fix: add default extension type

- packages/interface-address-manager/src/index.ts
When we observe an address that might be externally dialable (via identify or uPNP NAT holepunching, etc), we need some way of signalling that we've either verified it's externally dialable and that we are safe to advertise it, or that it's not dialable and that we should forget about it.
These methods are necessary to implement autonat.
> feat!: add observed address methods

- packages/interface-pubsub-compliance-tests/src/api.ts
- packages/interface-pubsub-compliance-tests/src/two-nodes.ts
- packages/interface-pubsub/src/index.ts
resolves #297 
- topicValidation is indeed specified in https://github.com/libp2p/specs/blob/master/pubsub/README.md#topic-validation
Still need to:
> fix!: add topicValidators to pubsub interface

- packages/interface-connection-encrypter-compliance-tests/package.json
- packages/interface-content-routing/package.json
- packages/interface-dht/package.json
- packages/interface-keychain/package.json
- packages/interface-mocks/package.json
- packages/interface-mocks/src/connection-manager.ts
- packages/interface-mocks/src/connection.ts
- packages/interface-mocks/test/connection.spec.ts
- packages/interface-peer-discovery-compliance-tests/src/index.ts
- packages/interface-peer-id/package.json
- packages/interface-pubsub-compliance-tests/package.json
- packages/interface-pubsub-compliance-tests/src/api.ts
- packages/interface-pubsub-compliance-tests/src/connection-handlers.ts
- packages/interface-pubsub-compliance-tests/src/emit-self.ts
- packages/interface-pubsub-compliance-tests/src/index.ts
- packages/interface-pubsub-compliance-tests/src/messages.ts
- packages/interface-pubsub-compliance-tests/src/multiple-nodes.ts
- packages/interface-pubsub-compliance-tests/src/two-nodes.ts
- packages/interface-pubsub-compliance-tests/src/utils.ts
- packages/interface-stream-muxer-compliance-tests/package.json
- packages/interface-transport-compliance-tests/package.json
`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major `@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of indirectly via `@libp2p/components`
Refs https://github.com/libp2p/js-libp2p-components/issues/6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection
> fix!: remove @libp2p/components

- packages/interface-mocks/src/connection.ts
- packages/interface-mocks/src/upgrader.ts
In order to support compliance testing transports that supply their own muxers/encryption allow passing `UpgraderOptions` to the `MockUpgrader` to be passed on to the `MockConnection`.
> feat: allow passing muxer factory to mock upgrader

- packages/interface-metrics/src/index.ts
- packages/interface-mocks/src/metrics.ts
We don't use bigints for metrics anywhere and some scrapers like `prom-client` don't support them so leave them out of the interface for now.
> fix: metrics only need numbers

- packages/interface-peer-id/src/index.ts
To reduce duplication elsewhere, expose supported PeerId types
> feat: expose supported peer id types

- README.md
- packages/interface-libp2p/CHANGELOG.md
- packages/interface-libp2p/LICENSE
- packages/interface-libp2p/LICENSE-APACHE
- packages/interface-libp2p/LICENSE-MIT
- packages/interface-libp2p/README.md
- packages/interface-libp2p/package.json
- packages/interface-libp2p/src/index.ts
- packages/interface-libp2p/tsconfig.json
- packages/interfaces/src/errors.ts
- packages/interfaces/src/index.ts
Adds the interface that libp2p node instance implement so other modules can show what version of libp2p they support without having to depend on libp2p directly.
> feat: add libp2p interface

- packages/interface-transport/src/index.ts
So we don't need to export the transport manager from libp2p, add the `FaultTolerance` enum to the interface def.
> feat: add fault tolerance enum

- packages/interface-libp2p/src/index.ts
So we don't have to expose the registrar component, add a method to get the currently supported protocols
> fix: add getProtocols method, events, and identify service

- packages/interface-peer-discovery-compliance-tests/src/index.ts
The event listener listening to new peers should be attached before waiting for the execution of `discovery.start()` to finish
> fix: refactor peer discovery compliance test

- packages/interfaces/src/errors.ts
Adds [CodeError](https://github.com/libp2p/js-libp2p/issues/1269) to errors.ts
Related: https://github.com/libp2p/js-libp2p-crypto/pull/284#issuecomment-1324005434
Added public to props and code to match AbortCode style.
Also recently added the custom [Error.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name) property to [code-err](https://github.com/tabcat/code-err) implementation. Can remove it from this PR if not wanted.
@wemeetagain
> feat: add CodeError

- packages/interface-libp2p/src/index.ts
Expose the methods used to register and unregister topologies on the libp2p object itself.
> feat: add register and unregister methods to libp2p type

- packages/interface-keychain/package.json
- packages/interface-keychain/src/index.ts
This was missed in an earlier iteration.
> fix: add importPeer method to keychain interface

- packages/interface-connection-manager/src/index.ts
- packages/interface-mocks/src/connection-manager.ts
This has been in libp2p for ages but was missed on the interface.
> fix: accept multiaddr param when opening connections

- packages/interface-keychain/src/index.ts
This is available in libp2p but not the interface
> fix: add exportPeer method to keychain interface

- packages/interface-mocks/package.json
- packages/interface-mocks/src/connection-manager.ts
- packages/interface-mocks/src/connection.ts
- packages/interface-mocks/src/muxer.ts
Replaces [err-code](https://github.com/IndigoUnited/js-err-code/blob/master/index.js) with [CodeError](https://github.com/libp2p/js-libp2p-interfaces/pull/314)
Related: [js-libp2p#1269](https://github.com/libp2p/js-libp2p/issues/1269)
**Was not sure how to update dependencies**
Changes (affect interface-mocks package only)
- uses CodeError in place of err-code
Blockers
> fix: replace err-code with CodeError

- packages/interface-mocks/src/connection-manager.ts
- packages/interface-mocks/src/multiaddr-connection.ts
- packages/interface-mocks/src/muxer.ts
- packages/interface-mocks/src/upgrader.ts
- packages/interface-stream-muxer-compliance-tests/src/close-test.ts
* Dispatch a connection event as per the upgrader interface
* Simplify args for MockConnectionManager
* Use base64pad for MockMuxer data transfer
> fix: dispatch connection event from mock upgrader

- packages/interface-content-routing/src/index.ts
- packages/interface-peer-routing/src/index.ts
Remove references to other strategies, just say what the method implementation is supposed to do.
> docs: update content/peer routing interface comments

- .gitignore
- README.md
- packages/interface-connection-gater/LICENSE
- packages/interface-connection-gater/LICENSE-APACHE
- packages/interface-connection-gater/LICENSE-MIT
- packages/interface-connection-gater/README.md
- packages/interface-connection-gater/package.json
- packages/interface-connection-gater/src/index.ts
- packages/interface-connection-gater/tsconfig.json
- packages/interface-connection/src/index.ts
- packages/interface-mocks/package.json
- packages/interface-mocks/src/connection-gater.ts
Deprecates use of connection gater from `@libp2p/interface-connection` as it's not part of the maconn/connection/stream group and instead is a cross-cuttuing security concern.
Non breaking for now, we can remove the original gater interface at a later date.
> feat: split connection gater out into module

- packages/interface-pubsub-compliance-tests/src/two-nodes.ts
Promises should be rejected with an error not a string, otherwise the wrong type is thrown
> fix: reject promise with error not string

- packages/interface-mocks/src/connection-manager.ts
When closing all connections to a peer, the resulting connection list should be all connnections not to that peer.
> fix: filter closed connections properly

- packages/interface-connection-manager/src/index.ts
- packages/interface-libp2p/src/index.ts
- packages/interface-mocks/src/connection-manager.ts
See https://github.com/libp2p/js-libp2p/issues/1616 for more details
> feat: support batch dialling 

- packages/interface-mocks/package.json
- packages/interface-mocks/src/connection-encrypter.ts
- packages/interface-mocks/src/muxer.ts
`any-signal@4.x.x` adds a `.clear` method that removes `'abort'` listeners which can be a cause of memory leaks.
> deps: update any-signal to 4.x.x

- packages/interface-connection-gater/src/index.ts
Since we can now dial multiaddrs without a peer id attached, the peer id may not be present on the multiaddr so we cannot have a required peer id argument passed to `denyDialMultiaddr`.
If present it can be accessed by calling `getPeerId` on the multiaddr.
BREAKING CHANGE: the peer id argument has been removed from the `denyDialMultiaddr` method of the connection gater
> fix!: remove peer id argument from deny dial multiaddr

- packages/interface-connection-manager/src/index.ts
The connection manager is how components open and close connections, the dialer is an internal implementation detail of libp2p so remove it from the interface.
BREAKING CHANGE: the Dialer interface has been removed
> fix!: remove dialer interface from interface connection manager

- packages/interface-connection-manager/src/index.ts
- packages/interface-mocks/src/connection-manager.ts
Adds a method to expose the current dial queue
> feat: expose get dial queue method of connection manager

- packages/interface-connection-manager/package.json
- packages/interface-connection-manager/src/index.ts
- packages/interface-mocks/package.json
- packages/interface-mocks/src/connection-manager.ts
Exposes the collection of managed connections as a peer map.
> feat: expose get connection map method of connection manager

- packages/interface-libp2p/src/index.ts
Exposes `getDialQueue`, released in `libp2p@0.44.x`
> feat: expose dial queue inspection method

- packages/interface-connection/src/index.ts
- packages/interface-mocks/package.json
- packages/interface-mocks/src/connection.ts
To let tsc handle return types properly and avoid the `unknown` type.
> fix: specify stream sink return type

- packages/interface-peer-store/src/index.ts
Allow passing `undefined` as a tag/metadata value to peerstore methods to allow removal of existing tags/metadata.
> fix: allow deleting tags/metadata with undefined fields

- packages/interface-mocks/src/upgrader.ts
To ease upgrading and not force users to pass a dummy object in.
> fix: make events optional in mock upgrader

- packages/interface-mocks/src/peer-discovery.ts
- packages/interface-peer-discovery/src/index.ts
The export `symbol` from the `@libp2p/interface-peer-discovery` is too generic to use with modules that might implement peer discovery and something else so it's been renamed to `peerDiscovery`.
Objects with `peerDiscovery` symbol properties getters should return `PeerDiscovery` instances instead of `boolean` values.
BREAKING CHANGE: the `symbol` export is now named `peerDiscovery`
> feat!: rename peer discovery symbol to peerDiscovery

- packages/interface-libp2p/src/index.ts
This event is useful to evesdrop on network behaviour and helps to debug situations where a remote peer is sending bad data in it's identify response (for exapmle not including any routable addresses).
An event is better than opening a protocol stream and sending more requests as remotes will frequently reset streams if there are too many concurrent identify requests, etc.
> feat: add peer:identify event to libp2p

- packages/interface-peer-store/src/index.ts
This method lets gossipsub consume a peer record.
> fix: expose peerstore consume peer record method

- packages/interface-mocks/src/connection-manager.ts
Updates mock to behave similarly to the actual connection manager.
> fix: emit peer:connect events from mock connection manager

- packages/interface-transport/src/index.ts
To make transports that piggy-back on top of other transports able to report their multiaddrs more reliably, expose the getListeners function implemented by the transport manager.
> fix: expose getListeners method from the transport manager

- packages/interface-connection/src/index.ts
Since streams can be closed for reading independently of being closed for writing, add separate optional keys for these events in the stream timeline interface.
> feat: add closeRead and closeWrite to stream timeline properties

- packages/interface-stream-muxer/package.json
- packages/interface-stream-muxer/src/stream.ts
Adds an extendable stream class that implements all the logic for closing/half closing streams in a consistent way.
Largely extracted from `@libp2p/mplex` and working with `@libp2p/webrtc`.
> feat: add abstract stream class

- packages/interface-stream-muxer/package.json
Allows typescript to find the typedefs for the stream.js file.
> fix: update interface stream muxer config

- packages/interface-stream-muxer/src/stream.ts
If a stream implementation needs to return a promise let them do so, this allows them to implement internal backpressure by slowing down reads from the source passed to the sink function.
> fix: allow stream methods to be async

- packages/interface-stream-muxer-compliance-tests/src/close-test.ts
The pipe can throw when errors occur so handle the errors.
> fix: handle thrown errors

- packages/interface-connection/src/index.ts
When no handler has been registered for a protocol, the upgrader falls back to the default limit of 64 streams for the protocol on the current connection.
This PR adds a `maxOutboundStreams` option to `connection.newStream` that gives the user a way to override the default outgoing stream count without having to register a dummy handler.
> fix: add maxOutboundStreams option to connection.newStream
